---
- name: Include CA recipes
  include: ca.yml

- name: Create custom Diffie-Hellman parameters
  command: "openssl dhparam -out {{ INDIGOVR_CERT_DIR }}/dh2048.pem 2048"
  args:
    creates: "{{ INDIGOVR_CERT_DIR }}/dh2048.pem"
  notify:
    - Enable and start OpenVPN service

- name: Fix permissions to Diffie-Hellman parameters
  file:
    path: "{{ INDIGOVR_CERT_DIR }}/dh2048.pem"
    group: "{{ INDIGOVR_USER }}"
    mode: 0644

- name: Copy CRL to OpenVPN
  copy:
    src: "{{ INDIGOVR_CA_DIR }}/crl.pem"
    dest: "{{ INDIGOVR_CERT_DIR }}/crl.pem"
    group: "{{ INDIGOVR_USER }}"
    mode: 0644
    remote_src: yes
  notify:
    - Enable and start OpenVPN service

- name: Copy CA certificate to OpenVPN
  copy:
    src: "{{ INDIGOVR_CA_DIR }}/ca.crt"
    dest: "{{ INDIGOVR_CERT_DIR }}/ca.crt"
    group: "{{ INDIGOVR_USER }}"
    mode: 0644
    remote_src: yes
  notify:
    - Enable and start OpenVPN service

- name: Create client configuration directory
  file:
    path: /etc/openvpn/ccd
    state: directory
    mode: 0755
    owner: root
    group: "{{ INDIGOVR_USER }}"
  notify:
    - Enable and start OpenVPN service

- name: CSR
  include: openssl_csr.yml

- name: Copy CSR to CA
  copy:
    src: "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.csr"
    dest: "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.csr"
    remote_src: yes

- name: Sign certificate
  command: openssl ca -config "{{ INDIGOVR_CA_DIR }}/openssl.cnf" -extensions server -notext -batch -in "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.csr" -out "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"
  args:
    creates: "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"

- name: Copy certificate to OpenVPN
  copy:
    src: "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"
    dest: "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.crt"
    group: "{{ INDIGOVR_USER }}"
    mode: 0644
    remote_src: yes
  notify:
    - Enable and start OpenVPN service
