---
- name: Include CentOS recipes
  include: centos.yml
  when: ansible_distribution == 'CentOS'

- name: Include OpenVPN recipes
  include: openvpn.yml

- name: Include "{{INDIGOVR_NODE_TYPE}}" recipe
  include: "{{INDIGOVR_NODE_TYPE}}.yml"

- name: Enable and start OpenVPN service
  service:
    name: "openvpn@{{ INDIGOVR_NODE_TYPE }}"
    enabled: yes
    state: started
  when:
    - ansible_virtualization_type != "docker"