- name: Create private key
  shell: openssl genrsa -out "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.key" 4096
  args:
    creates: "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.key"

- name: Fix private key permissions
  file:
    path: "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.key"
    mode: 0400
    owner: root
    group: root

- name: Copy OpenSSL configuration
  template:
    src: openssl-csr.cnf.j2
    dest: "{{ INDIGOVR_CERT_DIR }}/openssl.cnf"
    owner: root
    group: root
    mode: 0600

- name:  Create CSR
  shell: openssl req -config "{{ INDIGOVR_CERT_DIR }}/openssl.cnf" -key "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.key" -new -out "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.csr"
  args:
    creates: "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.csr"

