---
- name: CSR
  include: openssl_csr.yml

- name: Fetch CSR
  fetch:
    src: "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.csr"
    dest: "/tmp/._indigovr_tmp_{{ INDIGOVR_CERT_NAME }}.csr"
    flat: yes
    fail_on_missing: yes

- name: Copy CSR to CA
  copy:
    src: "/tmp/._indigovr_tmp_{{ INDIGOVR_CERT_NAME }}.csr"
    dest: "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.csr"
  delegate_to: "{{ INDIGOVR_CENTRALPOINT_IP }}"
  become: true

- name: Check if certfile file already exists
  stat:
    path: "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"
  register: certfile
  delegate_to: "{{ INDIGOVR_CENTRALPOINT_IP }}"
  become: true

- block:
  - name: Revoke previous certificate
    command: openssl ca -config "{{ INDIGOVR_CA_DIR }}/openssl.cnf" -revoke "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt" 
  - name: Delete previous certificate
    command: rm -fv "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"
  when: certfile.stat.exists
  delegate_to: "{{ INDIGOVR_CENTRALPOINT_IP }}"
  become: true

- name: Sign certificate
  shell: openssl ca -config "{{ INDIGOVR_CA_DIR }}/openssl.cnf" -extensions usr_cert -notext -batch -in "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.csr" -out "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"
  delegate_to: "{{ INDIGOVR_CENTRALPOINT_IP }}"
  become: true

- name: Create client configuration
  template:
    src: ccd-standalone.j2
    dest: "/etc/openvpn/ccd/{{ ansible_fqdn }}"
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{ INDIGOVR_CENTRALPOINT_IP }}"
  become: true

- name: Fetch certificate
  fetch:
    src: "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"
    dest: "/tmp/._indigovr_tmp_{{ INDIGOVR_CERT_NAME }}.crt"
    flat: yes
    fail_on_missing: yes
  delegate_to: "{{ INDIGOVR_CENTRALPOINT_IP }}"
  become: true

- name: Fetch CA certificate
  fetch:
    src: "{{ INDIGOVR_CA_DIR }}/ca.crt"
    dest: "/tmp/.indigovr_tmp_ca.crt"
    flat: yes
    fail_on_missing: yes
  delegate_to: "{{ INDIGOVR_CENTRALPOINT_IP }}"
  become: true

- name: Copy certificate to OpenVPN
  copy:
    src: "/tmp/._indigovr_tmp_{{ INDIGOVR_CERT_NAME }}.crt"
    dest: "{{ INDIGOVR_CERT_DIR }}/{{ INDIGOVR_CERT_NAME }}.crt"
    group: "{{ INDIGOVR_USER }}"
    mode: 0644

- name: Copy CA certificate to OpenVPN
  copy:
    src: "/tmp/.indigovr_tmp_ca.crt"
    dest: "{{ INDIGOVR_CERT_DIR }}/ca.crt"
    group: "{{ INDIGOVR_USER }}"
    mode: 0644
